import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer'

const COLORS = {
  primary: '#0007cd',
  ink: '#0f0f0f',
  body: '#444444',
  muted: '#6b7280',
  surface: '#f3f4f6',
} as const

const styles = StyleSheet.create({
  page: { padding: 48, fontFamily: 'Helvetica', color: COLORS.ink },
  title: { fontSize: 22, fontWeight: 'bold', marginBottom: 6 },
  subtitle: { fontSize: 11, color: COLORS.muted, marginBottom: 28 },
  section: { marginBottom: 18 },
  heading: { fontSize: 13, fontWeight: 'bold', color: COLORS.primary, marginBottom: 6 },
  row: { flexDirection: 'row', marginBottom: 4 },
  label: { fontSize: 10, width: 200, color: COLORS.muted },
  value: { fontSize: 10, fontWeight: 'bold', color: COLORS.body },
  attestation: { marginTop: 24, padding: 14, backgroundColor: COLORS.surface, borderRadius: 6 },
  attestationLabel: { fontSize: 10, fontWeight: 'bold', marginBottom: 6 },
  attestationText: { fontSize: 9, color: COLORS.body, lineHeight: 1.6 },
  footer: { position: 'absolute', bottom: 30, left: 48, right: 48, fontSize: 8, color: COLORS.muted },
})

export type CompliancePdfProps = {
  orgName: string
  plan: string
  reportingPeriod: string
  totalUsers: number
  avgScore: number
  totalInteractions: number
  correctAnswers: number
  phishSent: number
  phishClicked: number
  phishReported: number
  generatedAt: string
}

function pct(numerator: number, denominator: number): number {
  return denominator > 0 ? Math.round((numerator / denominator) * 100) : 0
}

export function buildCompliancePdf(props: CompliancePdfProps) {
  const accuracy = pct(props.correctAnswers, props.totalInteractions)
  const clickRate = pct(props.phishClicked, props.phishSent)
  const reportRate = pct(props.phishReported, props.phishSent)
  const generatedDate = new Date(props.generatedAt).toLocaleDateString()

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Security Awareness Training Report</Text>
        <Text style={styles.subtitle}>
          {props.orgName} — {props.plan.toUpperCase()} Plan
        </Text>

        <View style={styles.section}>
          <Text style={styles.heading}>Reporting Period</Text>
          <Text style={{ fontSize: 10, color: COLORS.body }}>{props.reportingPeriod}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Training Summary</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Total Employees Trained</Text>
            <Text style={styles.value}>{props.totalUsers}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Total Training Interactions</Text>
            <Text style={styles.value}>{props.totalInteractions}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Average Accuracy</Text>
            <Text style={styles.value}>{accuracy}%</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Average Risk Score</Text>
            <Text style={styles.value}>{props.avgScore}/100</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.heading}>Phishing Simulation Results</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Simulations Sent</Text>
            <Text style={styles.value}>{props.phishSent}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Click Rate</Text>
            <Text style={styles.value}>{clickRate}%</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Report Rate</Text>
            <Text style={styles.value}>{reportRate}%</Text>
          </View>
        </View>

        <View style={styles.attestation}>
          <Text style={styles.attestationLabel}>Attestation</Text>
          <Text style={styles.attestationText}>
            This report certifies that {props.orgName} has conducted ongoing security
            awareness training during the reporting period. Training includes daily
            interactive security challenges delivered via Slack/Microsoft Teams, phishing
            simulation exercises, and continuous Risk Score monitoring. All training
            activities are logged and auditable. Generated by DefendDaily on {generatedDate}.
          </Text>
        </View>

        <Text style={styles.footer}>
          DefendDaily Human Risk Management — Confidential — {props.generatedAt}
        </Text>
      </Page>
    </Document>
  )
}
